### ISSUE TITLE
missing function

### ISSUE THREAD

**Issue by ZZWENG** [yixchen/holistic_scene_human#3]
In inference_update.py Line 237, function `sit_hoi_model `is not defined anywhere in the code base. Could you provide complete code for this project? Thanks.

**Comment by yixchen** [comment]
Hi, sorry for the late reply. The typo has been fixed now. It should be the `hoi_model` class.

**Comment by ZZWENG** [comment]
> Hi, sorry for the late reply. The typo has been fixed now. It should be the `hoi_model` class.

thank you!
