### ISSUE TITLE
How is the HOI prior obtained?

### ISSUE THREAD

**Issue by xiexh20** [yixchen/holistic_scene_human#4]
Dear authors,

Thanks for the great work! I am impressed by the results you obtained. But I have a question about the interaction term used in your optimization pipeline. 
In the main paper after equation 5, you said _the likelihood can be learned from 3D HOI datasets_, can you specify which dataset you used to learn this prior? I also checked the source code [here](https://github.com/yixchen/holistic_scene_human/blob/338b1cea172864b03451fd2f8e347ab751f5e70a/src/inference_update.py#L213), how are these mean and variances computed? 

Thank you very much for your help!

Best,

**Comment by yixchen** [comment]
HI,

The dataset we used to capture the human-object interaction is collected from a video game Grand Theft Auto V, similar to GTA Indoor Motion dataset (GTA-IM) by Cao et al. Our dataset is under review. Still, you can get similar data from the existing dataset. The mean and variance are computed with 3D human skeletons and object bounding boxes by fitting a Gaussian mixture model between the human and object key points. For example, the sitting relation is calculated between the hip joint and the chair bounding box center. Such probabilistic models can be modified according to which granularity you want to model the HOI relationship.

Hope this helps.

**Comment by xiexh20** [comment]
Thank you very much for your detailed response. Now I have a better understanding of the method. 

Best of luck with your dataset review!
