### ISSUE TITLE
Trying to run inference but it just stalls?

### ISSUE THREAD

**Issue by MrXandbadas** [yixchen/holistic_scene_human#5]
Can't seem to reproduce a working example with the provided instructions.
I have the data and am trying to run the file with the parameters as the readme states

I receive a warning :
 RuntimeWarning: overflow encountered in exp
Then it stalls

**Comment by yixchen** [comment]
Hi,

Normally this warning won't stop the function, which could be ignored. The function will take ~30-40 seconds to infer on one image. Please include your environment, commands, and detailed error traceback for further analysis.

Thanks

**Comment by MrXandbadas** [comment]
`(venv) E:\3dHollistic\holistic_scene_human\src>python inference_natural_image.py --image_name frame1  
E:\3dHollistic\holistic_scene_human\src\mcmc.py:15: RuntimeWarning: overflow encountered in exp
  proposal = (Q_yx / Q_xy) * np.exp(-(Ey - Ex) / T)                                            
time elapsed: 227.6157398223877
[ WARN:0@227.825] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('../data\result\frame1\data\image\frame1_result.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):                                                                
  File "E:\3dHollistic\holistic_scene_human\src\inference_natural_image.py", line 166, in <module>
    main()                                                                                                                                                                 
  File "E:\3dHollistic\holistic_scene_human\src\inference_natural_image.py", line 162, in main                                                                             
    infer_image(arglist)                                                                                                                                                   
  File "E:\3dHollistic\holistic_scene_human\src\inference_natural_image.py", line 157, in infer_image                                                                      
    vis_all_multi(sampler, image_path, result_path, save_image=True)                                                                                                       
  File "E:\3dHollistic\holistic_scene_human\src\visulization.py", line 426, in vis_all_multi                                                                               
    ax2.imshow(cv2.cvtColor(image_2d_detection, cv2.COLOR_BGR2RGB))                                                                                                        
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
`

Thats my most recent error,

Im running Windows10, virtual Environment. Its a rig I built in 2015 So I don't expect it to be the best xD

---
Edit:
I know you have previously said you haven't tested on windows as it isn't your native OS. Although I was still hoping you may shed some light on the error :P

**Comment by yixchen** [comment]
This shows a visualization `OpenCV` error in `"..\holistic_scene_human\src\visulization.py", line 426, in vis_all_multi ax2.imshow(cv2.cvtColor(image_2d_detection, cv2.COLOR_BGR2RGB)) cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor''`. Make sure you have read all the images correctly in that function, i.e., `vis_all_multi` in `holistic_scene_human\src\visulization.py`.
